baseURL = 'https://jorisalkema.nl/'
title = "á••( á› )á•— Joris's website"
theme = 'hugo-bearcub'
copyright = 'Â© [Joris Duurt Cornelis Alkema]'

enableRobotsTXT = true
defaultContentLanguage = 'nl'

[languages.nl]
  languageName = "NL ğŸ‡³ğŸ‡±"
  languageCode = "nl-nl"
  contentDir = "content.nl"
  weight = 1

  # Dutch Menu (Translated!)
  [[languages.nl.menu.main]]
    identifier = "home"
    name = "Thuis"
    url = "/"
    weight = 10
  [[languages.nl.menu.main]]
    identifier = "about"
    name = "Over mij"
    url = "/about/"
    weight = 20
  [[languages.nl.menu.main]]
    identifier = "resume"
    name = "CV"
    url = "/resume.pdf"
    weight = 30
  [[languages.nl.menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 40
  [[languages.nl.menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 50

[languages.en]
  languageName = "en-UK ğŸ‡¬ğŸ‡§"
  languageCode = "en-gb"
  contentDir = "content"
  weight = 2

  # English Menu
  [[languages.en.menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[languages.en.menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 20
  [[languages.en.menu.main]]
    identifier = "resume"
    name = "Resume"
    url = "/resume.pdf"
    weight = 30
  [[languages.en.menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 40
  [[languages.en.menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 50

# BearBlog specific settings
[params]
  description = "A minimal blog."

disableKinds = ["RSS"]