baseURL = 'https://jorisalkema.nl/'
languageCode = 'en-us'
title = "á••( á› )á•— Joris's website"
theme = 'hugo-bearcub'
copyright = 'Â© [Joris Duurt Cornelis Alkema]'

hideUntranslated = false
enableRobotsTXT = true

[languages]
  [languages.en]
	title = "á••( á› )á•— Joris's website"
    languageName = "en-UK ğŸ‡¬ğŸ‡§"
    LanguageCode = "en-UK"
    contentDir = "content"
  [languages.pt]
	title = "á••( á› )á•— Joris's website"
    languageName = "NL ğŸ‡³ğŸ‡±"
    LanguageCode = "nl"
    contentDir = "content.nl"

# BearBlog specific settings
[params]
  description = "A minimal blog."

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 20

	[[menu.main]]
	identifier = "resume"
	name = "Resume"
	url = "/resume.pdf"
	weight = 30

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 40

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 50